#!/usr/bin/env bash
# PreToolUse hook: block edits to auto-generated files
# Receives tool input as JSON on stdin

set -euo pipefail

FILE_PATH=$(cat /dev/stdin | python3 -c "
import sys, json
data = json.load(sys.stdin)
print(data.get('file_path', ''))
" 2>/dev/null || echo "")

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

case "$FILE_PATH" in
  */config/crd/bases/*)
    echo "BLOCKED: config/crd/bases/ files are auto-generated by kubebuilder. Run 'make manifests' instead." >&2
    exit 2
    ;;
  */config/rbac/role.yaml)
    echo "BLOCKED: config/rbac/role.yaml is auto-generated by kubebuilder. Run 'make manifests' instead." >&2
    exit 2
    ;;
  */config/webhook/manifests.yaml)
    echo "BLOCKED: config/webhook/manifests.yaml is auto-generated by kubebuilder. Run 'make manifests' instead." >&2
    exit 2
    ;;
  *zz_generated*.go)
    echo "BLOCKED: zz_generated files are auto-generated by controller-gen. Run 'make generate' instead." >&2
    exit 2
    ;;
  */internal/grpc/gen/*)
    echo "BLOCKED: internal/grpc/gen/ files are auto-generated by buf. Run 'make proto' instead." >&2
    exit 2
    ;;
  */web/src/gen/*)
    echo "BLOCKED: web/src/gen/ files are auto-generated by buf. Run 'make proto' instead." >&2
    exit 2
    ;;
esac

exit 0
