version: 2

before:
  hooks:
    - go mod download

builds:
  - id: sreportal
    main: ./cmd
    binary: sreportal
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    goamd64:
      - v2
    ldflags:
      - -s -w
      - -X github.com/golgoth31/sreportal/internal/version.Version={{ .Version }}
      - -X github.com/golgoth31/sreportal/internal/version.Commit={{ .Commit }}
      - -X github.com/golgoth31/sreportal/internal/version.Date={{ .Date }}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^Merge pull request"
  use: github

release:
  mode: replace
  replace_existing_artifacts: true

kos:
  - build: sreportal
    base_image: cgr.dev/chainguard/static
    labels:
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "{{ .Major }}"
      - "{{ .Major }}.{{ .Minor }}"
      - "{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    sbom: spdx
    repositories:
      - ghcr.io/golgoth31/sreportal
    bare: true

snapshot:
  version_template: "v0.0.0-snapshot"
