FROM gcr.io/distroless/static:nonroot
ARG TARGETPLATFORM
WORKDIR /
COPY ${TARGETPLATFORM}/sreportal /sreportal
COPY web/dist/web/browser /web/dist/web/browser
USER 65532:65532

ENTRYPOINT ["/sreportal"]
