apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-auth
  labels:
  {{- include "helm.labels" . | nindent 4 }}
data:
  config.yaml: {{ required "auth.configYaml is required" .Values.auth.configYaml
    | b64enc | quote }}
type: Opaque
