apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "helm.fullname" . }}-manager-role
  labels:
  {{- include "helm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domain.scaleway.upbound.io
  resources:
  - records
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - grpcroutes
  - httproutes
  - tcproutes
  - tlsroutes
  - udproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.gke.io
  resources:
  - fqdnnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sreportal.io
  resources:
  - alertmanagers
  - components
  - dns
  - dnsrecords
  - incidents
  - maintenances
  - networkflowdiscoveries
  - portals
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sreportal.io
  resources:
  - alertmanagers/finalizers
  - components/finalizers
  - dns/finalizers
  - dnsrecords/finalizers
  - incidents/finalizers
  - maintenances/finalizers
  - networkflowdiscoveries/finalizers
  - portals/finalizers
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - sreportal.io
  resources:
  - alertmanagers/status
  - components/status
  - dns/status
  - dnsrecords/status
  - flowedgesets/status
  - flownodesets/status
  - incidents/status
  - maintenances/status
  - networkflowdiscoveries/status
  - portals/status
  - releases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sreportal.io
  resources:
  - flowedgesets
  - flownodesets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "helm.fullname" . }}-manager-rolebinding
  labels:
  {{- include "helm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "helm.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "helm.serviceAccountName" . }}'
  namespace: '{{ .Release.Namespace }}'
