---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domain.scaleway.upbound.io
  resources:
  - records
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - grpcroutes
  - httproutes
  - tcproutes
  - tlsroutes
  - udproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.gke.io
  resources:
  - fqdnnetworkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  - virtualservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - sreportal.io
  resources:
  - alertmanagers
  - dns
  - dnsrecords
  - networkflowdiscoveries
  - portals
  - releases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sreportal.io
  resources:
  - alertmanagers/finalizers
  - dns/finalizers
  - dnsrecords/finalizers
  - networkflowdiscoveries/finalizers
  - portals/finalizers
  - releases/finalizers
  verbs:
  - update
- apiGroups:
  - sreportal.io
  resources:
  - alertmanagers/status
  - dns/status
  - dnsrecords/status
  - flowedgesets/status
  - flownodesets/status
  - networkflowdiscoveries/status
  - portals/status
  - releases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - sreportal.io
  resources:
  - flowedgesets
  - flownodesets
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
