// Simplified subset of Hubble Observer service from cilium/cilium v1.19.2.
// Only the RPCs and types needed by the SRE Portal flow observer are included.
// Original source: https://github.com/cilium/cilium/blob/v1.19.2/api/v1/observer/observer.proto
//
// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Hubble

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: observer/observer.proto

package observer

import (
	flow "github.com/golgoth31/sreportal/internal/flowobserver/hubblegen/flow"
	relay "github.com/golgoth31/sreportal/internal/flowobserver/hubblegen/relay"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Symbols defined in public import of flow/flow.proto.

type Verdict = flow.Verdict

const Verdict_VERDICT_UNKNOWN = flow.Verdict_VERDICT_UNKNOWN
const Verdict_FORWARDED = flow.Verdict_FORWARDED
const Verdict_DROPPED = flow.Verdict_DROPPED
const Verdict_ERROR = flow.Verdict_ERROR
const Verdict_AUDIT = flow.Verdict_AUDIT
const Verdict_REDIRECTED = flow.Verdict_REDIRECTED
const Verdict_TRACED = flow.Verdict_TRACED
const Verdict_TRANSLATED = flow.Verdict_TRANSLATED

var Verdict_name = flow.Verdict_name
var Verdict_value = flow.Verdict_value

type LostEvent_Source = flow.LostEvent_Source

const LostEvent_UNKNOWN_LOST_EVENT_SOURCE = flow.LostEvent_UNKNOWN_LOST_EVENT_SOURCE
const LostEvent_PERF_EVENT_RING_BUFFER = flow.LostEvent_PERF_EVENT_RING_BUFFER
const LostEvent_OBSERVER_EVENTS_QUEUE = flow.LostEvent_OBSERVER_EVENTS_QUEUE
const LostEvent_HUBBLE_RING_BUFFER = flow.LostEvent_HUBBLE_RING_BUFFER

var LostEvent_Source_name = flow.LostEvent_Source_name
var LostEvent_Source_value = flow.LostEvent_Source_value

type Flow = flow.Flow
type Endpoint = flow.Endpoint
type Workload = flow.Workload
type FlowFilter = flow.FlowFilter
type LostEvent = flow.LostEvent

type ServerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusRequest) Reset() {
	*x = ServerStatusRequest{}
	mi := &file_observer_observer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusRequest) ProtoMessage() {}

func (x *ServerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observer_observer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusRequest.ProtoReflect.Descriptor instead.
func (*ServerStatusRequest) Descriptor() ([]byte, []int) {
	return file_observer_observer_proto_rawDescGZIP(), []int{0}
}

type ServerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumFlows      uint64                 `protobuf:"varint,1,opt,name=num_flows,json=numFlows,proto3" json:"num_flows,omitempty"`
	MaxFlows      uint64                 `protobuf:"varint,2,opt,name=max_flows,json=maxFlows,proto3" json:"max_flows,omitempty"`
	SeenFlows     uint64                 `protobuf:"varint,3,opt,name=seen_flows,json=seenFlows,proto3" json:"seen_flows,omitempty"`
	UptimeNs      uint64                 `protobuf:"varint,4,opt,name=uptime_ns,json=uptimeNs,proto3" json:"uptime_ns,omitempty"` // Fields 5-9 omitted (connected/unavailable nodes, version, flows_rate).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStatusResponse) Reset() {
	*x = ServerStatusResponse{}
	mi := &file_observer_observer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatusResponse) ProtoMessage() {}

func (x *ServerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observer_observer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatusResponse.ProtoReflect.Descriptor instead.
func (*ServerStatusResponse) Descriptor() ([]byte, []int) {
	return file_observer_observer_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStatusResponse) GetNumFlows() uint64 {
	if x != nil {
		return x.NumFlows
	}
	return 0
}

func (x *ServerStatusResponse) GetMaxFlows() uint64 {
	if x != nil {
		return x.MaxFlows
	}
	return 0
}

func (x *ServerStatusResponse) GetSeenFlows() uint64 {
	if x != nil {
		return x.SeenFlows
	}
	return 0
}

func (x *ServerStatusResponse) GetUptimeNs() uint64 {
	if x != nil {
		return x.UptimeNs
	}
	return 0
}

type GetFlowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number limits returned flows. Incompatible with since/until.
	Number uint64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"` // Fields 2 reserved, 9 (first) omitted.
	// follow keeps the stream open after returning buffered flows.
	Follow bool `protobuf:"varint,3,opt,name=follow,proto3" json:"follow,omitempty"`
	// blacklist excludes matching flows.
	Blacklist []*flow.FlowFilter `protobuf:"bytes,5,rep,name=blacklist,proto3" json:"blacklist,omitempty"`
	// whitelist includes only matching flows.
	Whitelist []*flow.FlowFilter `protobuf:"bytes,6,rep,name=whitelist,proto3" json:"whitelist,omitempty"`
	// since returns flows after this timestamp. Incompatible with number.
	Since *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=since,proto3" json:"since,omitempty"`
	// until returns flows before this timestamp. Incompatible with number.
	Until         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowsRequest) Reset() {
	*x = GetFlowsRequest{}
	mi := &file_observer_observer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowsRequest) ProtoMessage() {}

func (x *GetFlowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_observer_observer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowsRequest.ProtoReflect.Descriptor instead.
func (*GetFlowsRequest) Descriptor() ([]byte, []int) {
	return file_observer_observer_proto_rawDescGZIP(), []int{2}
}

func (x *GetFlowsRequest) GetNumber() uint64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *GetFlowsRequest) GetFollow() bool {
	if x != nil {
		return x.Follow
	}
	return false
}

func (x *GetFlowsRequest) GetBlacklist() []*flow.FlowFilter {
	if x != nil {
		return x.Blacklist
	}
	return nil
}

func (x *GetFlowsRequest) GetWhitelist() []*flow.FlowFilter {
	if x != nil {
		return x.Whitelist
	}
	return nil
}

func (x *GetFlowsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *GetFlowsRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type GetFlowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ResponseTypes:
	//
	//	*GetFlowsResponse_Flow
	//	*GetFlowsResponse_NodeStatus
	//	*GetFlowsResponse_LostEvents
	ResponseTypes isGetFlowsResponse_ResponseTypes `protobuf_oneof:"response_types"`
	NodeName      string                           `protobuf:"bytes,1000,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Time          *timestamppb.Timestamp           `protobuf:"bytes,1001,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFlowsResponse) Reset() {
	*x = GetFlowsResponse{}
	mi := &file_observer_observer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFlowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFlowsResponse) ProtoMessage() {}

func (x *GetFlowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_observer_observer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFlowsResponse.ProtoReflect.Descriptor instead.
func (*GetFlowsResponse) Descriptor() ([]byte, []int) {
	return file_observer_observer_proto_rawDescGZIP(), []int{3}
}

func (x *GetFlowsResponse) GetResponseTypes() isGetFlowsResponse_ResponseTypes {
	if x != nil {
		return x.ResponseTypes
	}
	return nil
}

func (x *GetFlowsResponse) GetFlow() *flow.Flow {
	if x != nil {
		if x, ok := x.ResponseTypes.(*GetFlowsResponse_Flow); ok {
			return x.Flow
		}
	}
	return nil
}

func (x *GetFlowsResponse) GetNodeStatus() *relay.NodeStatusEvent {
	if x != nil {
		if x, ok := x.ResponseTypes.(*GetFlowsResponse_NodeStatus); ok {
			return x.NodeStatus
		}
	}
	return nil
}

func (x *GetFlowsResponse) GetLostEvents() *flow.LostEvent {
	if x != nil {
		if x, ok := x.ResponseTypes.(*GetFlowsResponse_LostEvents); ok {
			return x.LostEvents
		}
	}
	return nil
}

func (x *GetFlowsResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GetFlowsResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type isGetFlowsResponse_ResponseTypes interface {
	isGetFlowsResponse_ResponseTypes()
}

type GetFlowsResponse_Flow struct {
	Flow *flow.Flow `protobuf:"bytes,1,opt,name=flow,proto3,oneof"`
}

type GetFlowsResponse_NodeStatus struct {
	NodeStatus *relay.NodeStatusEvent `protobuf:"bytes,2,opt,name=node_status,json=nodeStatus,proto3,oneof"`
}

type GetFlowsResponse_LostEvents struct {
	LostEvents *flow.LostEvent `protobuf:"bytes,3,opt,name=lost_events,json=lostEvents,proto3,oneof"`
}

func (*GetFlowsResponse_Flow) isGetFlowsResponse_ResponseTypes() {}

func (*GetFlowsResponse_NodeStatus) isGetFlowsResponse_ResponseTypes() {}

func (*GetFlowsResponse_LostEvents) isGetFlowsResponse_ResponseTypes() {}

var File_observer_observer_proto protoreflect.FileDescriptor

const file_observer_observer_proto_rawDesc = "" +
	"\n" +
	"\x17observer/observer.proto\x12\bobserver\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fflow/flow.proto\x1a\x11relay/relay.proto\"\x15\n" +
	"\x13ServerStatusRequest\"\x8c\x01\n" +
	"\x14ServerStatusResponse\x12\x1b\n" +
	"\tnum_flows\x18\x01 \x01(\x04R\bnumFlows\x12\x1b\n" +
	"\tmax_flows\x18\x02 \x01(\x04R\bmaxFlows\x12\x1d\n" +
	"\n" +
	"seen_flows\x18\x03 \x01(\x04R\tseenFlows\x12\x1b\n" +
	"\tuptime_ns\x18\x04 \x01(\x04R\buptimeNs\"\x85\x02\n" +
	"\x0fGetFlowsRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x04R\x06number\x12\x16\n" +
	"\x06follow\x18\x03 \x01(\bR\x06follow\x12.\n" +
	"\tblacklist\x18\x05 \x03(\v2\x10.flow.FlowFilterR\tblacklist\x12.\n" +
	"\twhitelist\x18\x06 \x03(\v2\x10.flow.FlowFilterR\twhitelist\x120\n" +
	"\x05since\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\x84\x02\n" +
	"\x10GetFlowsResponse\x12 \n" +
	"\x04flow\x18\x01 \x01(\v2\n" +
	".flow.FlowH\x00R\x04flow\x129\n" +
	"\vnode_status\x18\x02 \x01(\v2\x16.relay.NodeStatusEventH\x00R\n" +
	"nodeStatus\x122\n" +
	"\vlost_events\x18\x03 \x01(\v2\x0f.flow.LostEventH\x00R\n" +
	"lostEvents\x12\x1c\n" +
	"\tnode_name\x18\xe8\a \x01(\tR\bnodeName\x12/\n" +
	"\x04time\x18\xe9\a \x01(\v2\x1a.google.protobuf.TimestampR\x04timeB\x10\n" +
	"\x0eresponse_types2\xa2\x01\n" +
	"\bObserver\x12E\n" +
	"\bGetFlows\x12\x19.observer.GetFlowsRequest\x1a\x1a.observer.GetFlowsResponse\"\x000\x01\x12O\n" +
	"\fServerStatus\x12\x1d.observer.ServerStatusRequest\x1a\x1e.observer.ServerStatusResponse\"\x00BIZGgithub.com/golgoth31/sreportal/internal/flowobserver/hubblegen/observerP\x01b\x06proto3"

var (
	file_observer_observer_proto_rawDescOnce sync.Once
	file_observer_observer_proto_rawDescData []byte
)

func file_observer_observer_proto_rawDescGZIP() []byte {
	file_observer_observer_proto_rawDescOnce.Do(func() {
		file_observer_observer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_observer_observer_proto_rawDesc), len(file_observer_observer_proto_rawDesc)))
	})
	return file_observer_observer_proto_rawDescData
}

var file_observer_observer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_observer_observer_proto_goTypes = []any{
	(*ServerStatusRequest)(nil),   // 0: observer.ServerStatusRequest
	(*ServerStatusResponse)(nil),  // 1: observer.ServerStatusResponse
	(*GetFlowsRequest)(nil),       // 2: observer.GetFlowsRequest
	(*GetFlowsResponse)(nil),      // 3: observer.GetFlowsResponse
	(*flow.FlowFilter)(nil),       // 4: flow.FlowFilter
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*flow.Flow)(nil),             // 6: flow.Flow
	(*relay.NodeStatusEvent)(nil), // 7: relay.NodeStatusEvent
	(*flow.LostEvent)(nil),        // 8: flow.LostEvent
}
var file_observer_observer_proto_depIdxs = []int32{
	4,  // 0: observer.GetFlowsRequest.blacklist:type_name -> flow.FlowFilter
	4,  // 1: observer.GetFlowsRequest.whitelist:type_name -> flow.FlowFilter
	5,  // 2: observer.GetFlowsRequest.since:type_name -> google.protobuf.Timestamp
	5,  // 3: observer.GetFlowsRequest.until:type_name -> google.protobuf.Timestamp
	6,  // 4: observer.GetFlowsResponse.flow:type_name -> flow.Flow
	7,  // 5: observer.GetFlowsResponse.node_status:type_name -> relay.NodeStatusEvent
	8,  // 6: observer.GetFlowsResponse.lost_events:type_name -> flow.LostEvent
	5,  // 7: observer.GetFlowsResponse.time:type_name -> google.protobuf.Timestamp
	2,  // 8: observer.Observer.GetFlows:input_type -> observer.GetFlowsRequest
	0,  // 9: observer.Observer.ServerStatus:input_type -> observer.ServerStatusRequest
	3,  // 10: observer.Observer.GetFlows:output_type -> observer.GetFlowsResponse
	1,  // 11: observer.Observer.ServerStatus:output_type -> observer.ServerStatusResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_observer_observer_proto_init() }
func file_observer_observer_proto_init() {
	if File_observer_observer_proto != nil {
		return
	}
	file_observer_observer_proto_msgTypes[3].OneofWrappers = []any{
		(*GetFlowsResponse_Flow)(nil),
		(*GetFlowsResponse_NodeStatus)(nil),
		(*GetFlowsResponse_LostEvents)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_observer_observer_proto_rawDesc), len(file_observer_observer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_observer_observer_proto_goTypes,
		DependencyIndexes: file_observer_observer_proto_depIdxs,
		MessageInfos:      file_observer_observer_proto_msgTypes,
	}.Build()
	File_observer_observer_proto = out.File
	file_observer_observer_proto_goTypes = nil
	file_observer_observer_proto_depIdxs = nil
}
