## Append samples of your project ##
resources:
- sreportal_v1alpha1_dns.yaml
- sreportal_v1alpha1_portal.yaml
- v1alpha1_alertmanager.yaml
- v1alpha1_release.yaml
- v1alpha1_networkflowdiscovery.yaml
- v1alpha1_flownodeset.yaml
- v1alpha1_flowedgeset.yaml
- v1alpha1_component.yaml
- v1alpha1_maintenance.yaml
- v1alpha1_incident.yaml
- v1alpha1_flowobserver.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
