apiVersion: sreportal.io/v1alpha2
kind: DNS
metadata:
  name: main
  namespace: sreportal-system
spec:
  portalRef: main
  sources:
    ingress:
      enabled: true
      annotationFilter: "external-dns.alpha.kubernetes.io/hostname"
    service:
      enabled: true
      annotationFilter: "external-dns.alpha.kubernetes.io/hostname"
      serviceTypeFilter: [LoadBalancer]
    priority: [ingress, service]
  groupMapping:
    defaultGroup: Services
    labelKey: sreportal.io/group
    byNamespace:
      monitoring: Monitoring
      default: Development
  reconciliation:
    interval: 5m
    retryOnError: 30s
    disableDNSCheck: false
