apiVersion: v1
kind: Service
metadata:
  name: nginx-test2
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "nginx2.example.com"
    sreportal.io/groups: Applications
spec:
  type: LoadBalancer
  selector:
    app: nginx-test2
  ports:
    - port: 80
      targetPort: 80
