apiVersion: sreportal.io/v1alpha1
kind: Release
metadata:
  labels:
    app.kubernetes.io/name: sreportal
    app.kubernetes.io/managed-by: kustomize
  name: release-2026-03-28
spec:
  portalRef: main
  entries: []
