apiVersion: sreportal.io/v1alpha1
kind: FlowObserver
metadata:
  labels:
    app.kubernetes.io/name: sreportal
    app.kubernetes.io/managed-by: kustomize
  name: flowobserver-sample
spec:
  # TODO(user): Add fields here
