package grpc_test

const (
	tPortalMain       = "main"
	tFingerprintA     = "aaa"
	tAlertHighCPU     = "HighCPU"
	tAlertStateActive = "active"
	tFingerprintB     = "bbb"
	tNsDefault        = "default"
	tFQDNAPI          = "api.example.com"
	tFQDNInternal     = "internal.example.com"
	tNameAPI          = "api"
	tSubsystemDNS     = "dns"
	tMetricFQDNTotal  = "fqdns_total"
	tHelpFQDNTotal    = "Total FQDNs"
	tGroupCore        = "Core"
	tEdgeInternal     = "internal"
	tGroupPay         = "Pay"
	tKindDeployment   = "deployment"
	tNameCICD         = "ci/cd"
	tDate20260321     = "2026-03-21"

	tLabelAlertname     = "alertname"
	tNamespaceSreportal = "sreportal"
	tPortalMyPortal     = "my-portal"
	tNodeSvcWeb         = "svc:core:web"
	tEdgeExternal       = "external"
	tNodeSvcA           = "svc:core:a"
	tVerV1              = "v1.0.0"
	tStatusRollback     = "rollback"

	tNsCore           = "core"
	tNsWeb            = "web"
	tNsPay            = "pay"
	tNodeTypeService  = "service"
	tNameStripe       = "stripe"
	tNodeSvcCoreAPI   = "svc:core:api"
	tNodeSvcPayStripe = "svc:pay:stripe"
)
