# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
  - bases/sreportal.io_dnsrecords.yaml
  - bases/sreportal.io_dns.yaml
  - bases/sreportal.io_portals.yaml
  - bases/sreportal.io_alertmanagers.yaml
  - bases/sreportal.io_releases.yaml
  - bases/sreportal.io_networkflowdiscoveries.yaml
  - bases/sreportal.io_flownodesets.yaml
  - bases/sreportal.io_flowedgesets.yaml
  - bases/sreportal.io_components.yaml
  - bases/sreportal.io_maintenances.yaml
  - bases/sreportal.io_incidents.yaml
  - bases/sreportal.io_flowobservers.yaml
  - bases/sreportal.io_imageinventories.yaml
  - bases/sreportal.io_imageregistries.yaml
- bases/sreportal.io_deploystatuses.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# patches here are for enabling the conversion webhook for each CRD
patches:
  - path: patches/webhook_in_dns.yaml
  - path: patches/webhook_in_dnsrecords.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# Teaches kustomize how to substitute the webhook service name/namespace
# into spec.conversion.webhook.clientConfig.service.
configurations:
  - kustomizeconfig.yaml
