//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CommonSourceSpec) DeepCopyInto(out *CommonSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CommonSourceSpec.
func (in *CommonSourceSpec) DeepCopy() *CommonSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CommonSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CrossplaneScalewayRecordSourceSpec) DeepCopyInto(out *CrossplaneScalewayRecordSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CrossplaneScalewayRecordSourceSpec.
func (in *CrossplaneScalewayRecordSourceSpec) DeepCopy() *CrossplaneScalewayRecordSourceSpec {
	if in == nil {
		return nil
	}
	out := new(CrossplaneScalewayRecordSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNS) DeepCopyInto(out *DNS) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNS.
func (in *DNS) DeepCopy() *DNS {
	if in == nil {
		return nil
	}
	out := new(DNS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNS) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSEndpointSourceSpec) DeepCopyInto(out *DNSEndpointSourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSEndpointSourceSpec.
func (in *DNSEndpointSourceSpec) DeepCopy() *DNSEndpointSourceSpec {
	if in == nil {
		return nil
	}
	out := new(DNSEndpointSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSList) DeepCopyInto(out *DNSList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNS, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSList.
func (in *DNSList) DeepCopy() *DNSList {
	if in == nil {
		return nil
	}
	out := new(DNSList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecord) DeepCopyInto(out *DNSRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecord.
func (in *DNSRecord) DeepCopy() *DNSRecord {
	if in == nil {
		return nil
	}
	out := new(DNSRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordEntry) DeepCopyInto(out *DNSRecordEntry) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordEntry.
func (in *DNSRecordEntry) DeepCopy() *DNSRecordEntry {
	if in == nil {
		return nil
	}
	out := new(DNSRecordEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordList) DeepCopyInto(out *DNSRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DNSRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordList.
func (in *DNSRecordList) DeepCopy() *DNSRecordList {
	if in == nil {
		return nil
	}
	out := new(DNSRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DNSRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordSpec) DeepCopyInto(out *DNSRecordSpec) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]DNSRecordEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordSpec.
func (in *DNSRecordSpec) DeepCopy() *DNSRecordSpec {
	if in == nil {
		return nil
	}
	out := new(DNSRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSRecordStatus) DeepCopyInto(out *DNSRecordStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]EndpointStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSRecordStatus.
func (in *DNSRecordStatus) DeepCopy() *DNSRecordStatus {
	if in == nil {
		return nil
	}
	out := new(DNSRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSSpec) DeepCopyInto(out *DNSSpec) {
	*out = *in
	out.Defaults = in.Defaults
	in.Sources.DeepCopyInto(&out.Sources)
	in.GroupMapping.DeepCopyInto(&out.GroupMapping)
	out.Reconciliation = in.Reconciliation
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSSpec.
func (in *DNSSpec) DeepCopy() *DNSSpec {
	if in == nil {
		return nil
	}
	out := new(DNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DNSStatus) DeepCopyInto(out *DNSStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
	if in.ActiveSources != nil {
		in, out := &in.ActiveSources, &out.ActiveSources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NextReconcileTime != nil {
		in, out := &in.NextReconcileTime, &out.NextReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DNSStatus.
func (in *DNSStatus) DeepCopy() *DNSStatus {
	if in == nil {
		return nil
	}
	out := new(DNSStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointStatus) DeepCopyInto(out *EndpointStatus) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.LastSeen.DeepCopyInto(&out.LastSeen)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointStatus.
func (in *EndpointStatus) DeepCopy() *EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNGroupStatus) DeepCopyInto(out *FQDNGroupStatus) {
	*out = *in
	if in.FQDNs != nil {
		in, out := &in.FQDNs, &out.FQDNs
		*out = make([]FQDNStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNGroupStatus.
func (in *FQDNGroupStatus) DeepCopy() *FQDNGroupStatus {
	if in == nil {
		return nil
	}
	out := new(FQDNGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FQDNStatus) DeepCopyInto(out *FQDNStatus) {
	*out = *in
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.LastSeen.DeepCopyInto(&out.LastSeen)
	if in.OriginRef != nil {
		in, out := &in.OriginRef, &out.OriginRef
		*out = new(OriginResourceRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FQDNStatus.
func (in *FQDNStatus) DeepCopy() *FQDNStatus {
	if in == nil {
		return nil
	}
	out := new(FQDNStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRouteSourceSpec) DeepCopyInto(out *GatewayRouteSourceSpec) {
	*out = *in
	out.CommonSourceSpec = in.CommonSourceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRouteSourceSpec.
func (in *GatewayRouteSourceSpec) DeepCopy() *GatewayRouteSourceSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayRouteSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupMappingSpec) DeepCopyInto(out *GroupMappingSpec) {
	*out = *in
	if in.ByNamespace != nil {
		in, out := &in.ByNamespace, &out.ByNamespace
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupMappingSpec.
func (in *GroupMappingSpec) DeepCopy() *GroupMappingSpec {
	if in == nil {
		return nil
	}
	out := new(GroupMappingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IngressSourceSpec) DeepCopyInto(out *IngressSourceSpec) {
	*out = *in
	out.CommonSourceSpec = in.CommonSourceSpec
	if in.IngressClassNames != nil {
		in, out := &in.IngressClassNames, &out.IngressClassNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IngressSourceSpec.
func (in *IngressSourceSpec) DeepCopy() *IngressSourceSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioGatewaySourceSpec) DeepCopyInto(out *IstioGatewaySourceSpec) {
	*out = *in
	out.CommonSourceSpec = in.CommonSourceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioGatewaySourceSpec.
func (in *IstioGatewaySourceSpec) DeepCopy() *IstioGatewaySourceSpec {
	if in == nil {
		return nil
	}
	out := new(IstioGatewaySourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IstioVirtualServiceSourceSpec) DeepCopyInto(out *IstioVirtualServiceSourceSpec) {
	*out = *in
	out.CommonSourceSpec = in.CommonSourceSpec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IstioVirtualServiceSourceSpec.
func (in *IstioVirtualServiceSourceSpec) DeepCopy() *IstioVirtualServiceSourceSpec {
	if in == nil {
		return nil
	}
	out := new(IstioVirtualServiceSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OriginResourceRef) DeepCopyInto(out *OriginResourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OriginResourceRef.
func (in *OriginResourceRef) DeepCopy() *OriginResourceRef {
	if in == nil {
		return nil
	}
	out := new(OriginResourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReconciliationSpec) DeepCopyInto(out *ReconciliationSpec) {
	*out = *in
	out.Interval = in.Interval
	out.RetryOnError = in.RetryOnError
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReconciliationSpec.
func (in *ReconciliationSpec) DeepCopy() *ReconciliationSpec {
	if in == nil {
		return nil
	}
	out := new(ReconciliationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceSourceSpec) DeepCopyInto(out *ServiceSourceSpec) {
	*out = *in
	out.CommonSourceSpec = in.CommonSourceSpec
	if in.ServiceTypeFilter != nil {
		in, out := &in.ServiceTypeFilter, &out.ServiceTypeFilter
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceSourceSpec.
func (in *ServiceSourceSpec) DeepCopy() *ServiceSourceSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceSourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceFilterDefaults) DeepCopyInto(out *SourceFilterDefaults) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceFilterDefaults.
func (in *SourceFilterDefaults) DeepCopy() *SourceFilterDefaults {
	if in == nil {
		return nil
	}
	out := new(SourceFilterDefaults)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcesSpec) DeepCopyInto(out *SourcesSpec) {
	*out = *in
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(IngressSourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DNSEndpoint != nil {
		in, out := &in.DNSEndpoint, &out.DNSEndpoint
		*out = new(DNSEndpointSourceSpec)
		**out = **in
	}
	if in.IstioGateway != nil {
		in, out := &in.IstioGateway, &out.IstioGateway
		*out = new(IstioGatewaySourceSpec)
		**out = **in
	}
	if in.IstioVirtualService != nil {
		in, out := &in.IstioVirtualService, &out.IstioVirtualService
		*out = new(IstioVirtualServiceSourceSpec)
		**out = **in
	}
	if in.GatewayHTTPRoute != nil {
		in, out := &in.GatewayHTTPRoute, &out.GatewayHTTPRoute
		*out = new(GatewayRouteSourceSpec)
		**out = **in
	}
	if in.GatewayGRPCRoute != nil {
		in, out := &in.GatewayGRPCRoute, &out.GatewayGRPCRoute
		*out = new(GatewayRouteSourceSpec)
		**out = **in
	}
	if in.GatewayTLSRoute != nil {
		in, out := &in.GatewayTLSRoute, &out.GatewayTLSRoute
		*out = new(GatewayRouteSourceSpec)
		**out = **in
	}
	if in.GatewayTCPRoute != nil {
		in, out := &in.GatewayTCPRoute, &out.GatewayTCPRoute
		*out = new(GatewayRouteSourceSpec)
		**out = **in
	}
	if in.GatewayUDPRoute != nil {
		in, out := &in.GatewayUDPRoute, &out.GatewayUDPRoute
		*out = new(GatewayRouteSourceSpec)
		**out = **in
	}
	if in.CrossplaneScalewayRecord != nil {
		in, out := &in.CrossplaneScalewayRecord, &out.CrossplaneScalewayRecord
		*out = new(CrossplaneScalewayRecordSourceSpec)
		**out = **in
	}
	if in.Priority != nil {
		in, out := &in.Priority, &out.Priority
		*out = make([]SourceType, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcesSpec.
func (in *SourcesSpec) DeepCopy() *SourcesSpec {
	if in == nil {
		return nil
	}
	out := new(SourcesSpec)
	in.DeepCopyInto(out)
	return out
}
